import { lightTheme } from './light'
import { colorPalette } from './colorPalette'

export const darkTheme = {
	...lightTheme,
	primaryMain: colorPalette.blue_400,
	primaryLight: colorPalette.blue_200,
	primaryDark: colorPalette.blue_600,
	textMain: colorPalette.gray_200,
	textLight: colorPalette.gray_300,
	textLighter: colorPalette.gray_500,
	textDark: colorPalette.gray_500,
	backgroundLight: colorPalette.gray_900,
	backgroundMedium: colorPalette.gray_800,
	backgroundDark: colorPalette.gray_700,
	backgroundDarker: colorPalette.gray_600,
	borderColor: '#434F5C',
	logoColor: colorPalette.gray_100,
	type: {
		...lightTheme.type,
	},
	selectedItem: {
		color: colorPalette.blue_400,
		colorHover: colorPalette.blue_500,
		background: 'rgba(0,0,0,0.3)',
		backgroundHover: 'rgba(26,155,246,0.15)',
	},
	button: {
		...lightTheme.button,
		secondaryText: colorPalette.gray_100,
		secondaryBackgroundHover: 'rgba(26,155,246,0.15)',
		secondaryBorderHover: colorPalette.blue_700,
		secondaryTextHover: colorPalette.gray_50,
		errorBackground: colorPalette.red_500,
		errorText: colorPalette.gray_100,
		errorBackgroundHover: colorPalette.red_600,
		errorTextHover: colorPalette.gray_50,
		defaultText: colorPalette.gray_100,
		defaultTextHover: colorPalette.gray_50,
		defaultBackgroundHover: 'rgba(255,255,255,0.05)',
	},
	iconButton: {
		...lightTheme.iconButton,
		defaultBackground: 'rgba(0,0,0,0.3)',
		defaultIcon: colorPalette.blue_400,
		defaultBackgroundHover: 'rgba(26,155,246,0.15)',
		defaultIconHover: colorPalette.blue_500,
		secondaryBackground: 'transparent',
		secondaryIcon: colorPalette.gray_100,
		secondaryBorder: colorPalette.blue_400,
		secondaryBackgroundHover: 'rgba(26,155,246,0.15)',
		secondaryIconHover: colorPalette.gray_50,
		secondaryBorderHover: colorPalette.blue_600,
		errorBackground: colorPalette.red_500,
		errorIcon: colorPalette.gray_100,
		errorBackgroundHover: colorPalette.red_600,
		errorIconHover: colorPalette.gray_50,
		icon: colorPalette.gray_100,
		backgroundHover: 'rgba(255,255,255,0.05)',
		iconHover: colorPalette.gray_50,
	},
	input: {
		...lightTheme.input,
		background: 'rgba(0,0,0,0.3)',
		color: colorPalette.gray_100,
		colorIcon: colorPalette.gray_200,
		backgroundHover: 'rgba(0,0,0,0.4)',
		colorHover: colorPalette.gray_50,
		borderColor: colorPalette.blue_400,
		secondBorderColor: colorPalette.gray_700,
		secondBorderErrorColor: colorPalette.red_900,
	},
	switch: {
		track: colorPalette.gray_700,
		trackChecked: colorPalette.blue_400,
		thumb: colorPalette.gray_300,
		thumbChecked: colorPalette.blue_500,
	},
	dialog: {
		background: colorPalette.gray_900,
		buttonsBackground: colorPalette.gray_800,
	},
	contextMenu: {
		background: colorPalette.gray_700,
		color: colorPalette.gray_100,
		colorHover: colorPalette.gray_50,
		backgroundHover: colorPalette.gray_800,
		backgroundDanger: colorPalette.red_500,
		colorDanger: colorPalette.gray_100,
		backgroundDangerHover: colorPalette.red_600,
		colorDangerHover: colorPalette.gray_50,
		icon: colorPalette.gray_200,
		iconHover: colorPalette.gray_100,
		backgroundSelected: 'rgba(0,0,0,0.3)',
		backgroundSelectedHover: 'rgba(26,155,246,0.15)',
		colorSelected: colorPalette.blue_400,
		colorSelectedHover: colorPalette.blue_200,
	},
	mainLabel: {
		color: colorPalette.gray_100,
	},
	table: {
		...lightTheme.table,
		rowColor: colorPalette.gray_100,
		rowBackground: colorPalette.gray_900,
		borderColor: colorPalette.gray_700,
		selectedColor: colorPalette.blue_50,
		selectedBackground: 'rgba(0,0,0,0.3)',
		dragIndicator: colorPalette.gray_700,
		selectedDragIndicator: colorPalette.gray_600,
	},
	snackbar: {
		successTextColor: colorPalette.teal_50,
		successBackground: colorPalette.teal_400,
		errorTextColor: colorPalette.red_50,
		errorBackground: colorPalette.red_400,
		infoTextColor: colorPalette.blue_50,
		infoBackground: colorPalette.red_400,
		warningTextColor: colorPalette.yellow_50,
		warningBackground: colorPalette.yellow_400,
		defaultTextColor: colorPalette.gray_800,
		defaultBackground: colorPalette.gray_100,
	},
	assetCard: {
		...lightTheme.assetCard,
		background: 'transparent',
		backgroundSelected: 'rgba(0,0,0,0.3)',
		textMain: colorPalette.gray_50,
		textMainSelected: colorPalette.blue_400,
		textLight: colorPalette.gray_500,
		textLightSelected: colorPalette.blue_400,
		borderColor: '#434F5C',
		previewBackgroundSelected: colorPalette.blue_800,
	},
	cardType: {
		...lightTheme.cardType,
	},
	navItem: {
		background: 'transparent',
		color: colorPalette.gray_100,
		inheritedInfoColor: colorPalette.gray_400,
		inheritedBorderColor: colorPalette.gray_700,
		inheritedBackground: colorPalette.gray_900,
		inheritedColor: colorPalette.gray_600,
		selectedBackground: 'rgba(0,0,0,0.3)',
		selectedColor: colorPalette.blue_400,
		selectedInheritedBorderColor: colorPalette.gray_700,
	},
	list: {
		rowBackground: colorPalette.gray_800,
		rowBackgroundSelected: 'rgba(0,0,0,0.5)',
		rowBackgroundHover: colorPalette.gray_700,
		rowBackgroundSelectedHover: 'rgba(26,155,246,0.30)',
		headerBackground: colorPalette.gray_900,
		headerBackgroundSelected: 'rgba(0,0,0,0.3)',
		headerBackgroundHover: colorPalette.gray_800,
		headerBackgroundSelectedHover: 'rgba(26,155,246,0.15)',
	},
	message: {
		errorBackground: colorPalette.red_500,
		errorColor: colorPalette.red_50,
		warningBackground: colorPalette.yellow_500,
		warningColor: colorPalette.yellow_50,
		infoBackground: colorPalette.gray_500,
		infoColor: colorPalette.gray_50,
	},
	grantTypePill: {
		BrowserBackground: colorPalette.gray_600,
		BrowserNumberBackground: colorPalette.gray_700,
		BrowserColor: colorPalette.gray_100,
		STBBackground: colorPalette.purple_800,
		STBNumberBackground: colorPalette.purple_900,
		STBColor: colorPalette.purple_100,
		SignageBackground: colorPalette.teal_800,
		SignageNumberBackground: colorPalette.teal_900,
		SignageColor: colorPalette.teal_100,
		TabletBackground: colorPalette.blue_700,
		TabletNumberBackground: colorPalette.blue_800,
		TabletColor: colorPalette.blue_100,
		BedsideBackground: colorPalette.pink_800,
		BedsideNumberBackground: colorPalette.pink_900,
		BedsideColor: colorPalette.pink_100,
	},
}
