import { colorPalette } from './colorPalette'

export const lightTheme = {
	primaryMain: colorPalette.blue_500,
	primaryLight: colorPalette.blue_300,
	primaryDark: colorPalette.blue_700,
	primarySuperLight: colorPalette.blue_50,
	primaryContrastText: colorPalette.gray_100,
	textMain: colorPalette.gray_800,
	textLight: colorPalette.gray_600,
	textLighter: colorPalette.gray_500,
	textDark: colorPalette.gray_900,
	backgroundLight: colorPalette.gray_50,
	backgroundMedium: colorPalette.gray_100,
	backgroundDark: colorPalette.gray_200,
	backgroundDarker: colorPalette.gray_300,
	borderColor: colorPalette.gray_300,
	selectedItem: {
		color: colorPalette.blue_500,
		background: colorPalette.blue_100,
		backgroundHover: colorPalette.blue_200,
	},
	dangerMain: colorPalette.red_500,
	dangerLight: colorPalette.red_400,
	dangerDark: colorPalette.red_600,
	dangerSuperLight: colorPalette.red_50,
	type: {
		audioBackground: colorPalette.teal_50,
		audioColor: colorPalette.teal_600,
		channelBackground: colorPalette.blue_50,
		channelColor: colorPalette.blue_600,
		documentBackground: colorPalette.gray_200,
		documentColor: colorPalette.gray_600,
		imageBackground: colorPalette.yellow_50,
		imageColor: colorPalette.yellow_600,
		slideBackground: colorPalette.purple_50,
		slideColor: colorPalette.purple_500,
		videoBackground: colorPalette.pink_50,
		videoColor: colorPalette.pink_600,
		errorColor: colorPalette.red_600,
		errorBackground: colorPalette.red_50,
	},
	snackbar: {
		successTextColor: colorPalette.teal_50,
		successBackground: colorPalette.teal_500,
		errorTextColor: colorPalette.red_50,
		errorBackground: colorPalette.red_500,
		infoTextColor: colorPalette.blue_50,
		infoBackground: colorPalette.red_500,
		warningTextColor: colorPalette.yellow_50,
		warningBackground: colorPalette.yellow_500,
		defaultTextColor: colorPalette.gray_100,
		defaultBackground: colorPalette.gray_800,
	},
	tooltipBackground: 'rgba(62, 79, 95, 0.8)',
	tooltipColor: colorPalette.gray_100,
	greenMain: colorPalette.teal_400,
	greenLight: colorPalette.teal_300,
	greenDark: colorPalette.teal_500,
	greenSuperLight: colorPalette.teal_50,
	yellowMain: colorPalette.yellow_400,
	yellowLight: colorPalette.yellow_300,
	yellowDark: colorPalette.yellow_500,
	yellowSuperLight: colorPalette.yellow_50,
	redMain: colorPalette.red_400,
	redLight: colorPalette.red_300,
	redDark: colorPalette.red_500,
	redSuperLight: colorPalette.red_50,
	logoColor: colorPalette.blue_500,
	button: {
		primaryBackground: colorPalette.blue_500,
		primaryText: colorPalette.gray_100,
		primaryTextHover: colorPalette.gray_50,
		primaryBackgroundHover: colorPalette.blue_700,
		secondaryBorder: colorPalette.blue_500,
		secondaryText: colorPalette.blue_500,
		secondaryBackgroundHover: colorPalette.blue_50,
		secondaryBorderHover: colorPalette.blue_700,
		secondaryTextHover: colorPalette.blue_700,
		errorBackground: colorPalette.red_50,
		errorText: colorPalette.red_500,
		errorBackgroundHover: colorPalette.red_100,
		errorTextHover: colorPalette.red_600,
		defaultText: colorPalette.gray_800,
		defaultTextHover: colorPalette.gray_900,
		defaultBackgroundHover: colorPalette.gray_200,
	},
	iconButton: {
		defaultBackground: colorPalette.gray_200,
		defaultIcon: colorPalette.gray_800,
		defaultBackgroundHover: colorPalette.gray_300,
		defaultIconHover: colorPalette.gray_900,
		selectedBackground: colorPalette.blue_100,
		selectedIcon: colorPalette.blue_500,
		selectedBackgroundHover: colorPalette.blue_200,
		selectedIconHover: colorPalette.blue_700,
		secondaryBackground: 'transparent',
		secondaryIcon: colorPalette.blue_500,
		secondaryBorder: colorPalette.blue_500,
		secondaryBackgroundHover: colorPalette.blue_50,
		secondaryIconHover: colorPalette.blue_700,
		secondaryBorderHover: colorPalette.blue_700,
		errorBackground: colorPalette.red_50,
		errorIcon: colorPalette.red_500,
		errorBackgroundHover: colorPalette.red_100,
		errorIconHover: colorPalette.red_700,
		background: 'transparent',
		icon: colorPalette.gray_800,
		backgroundHover: colorPalette.gray_200,
		iconHover: colorPalette.gray_900,
	},
	input: {
		background: colorPalette.gray_200,
		color: colorPalette.gray_800,
		colorIcon: colorPalette.gray_700,
		backgroundHover: colorPalette.gray_300,
		colorHover: colorPalette.gray_900,
		borderColor: colorPalette.blue_500,
		secondBorderColor: colorPalette.blue_100,
		errorBorderColor: colorPalette.red_500,
		secondBorderErrorColor: colorPalette.red_100,
	},
	switch: {
		track: colorPalette.gray_300,
		trackChecked: colorPalette.blue_500,
		thumb: colorPalette.gray_100,
		thumbChecked: colorPalette.blue_500,
	},
	dialog: {
		background: colorPalette.gray_50,
		buttonsBackground: colorPalette.gray_200,
	},
	contextMenu: {
		background: colorPalette.gray_50,
		color: colorPalette.gray_800,
		colorHover: colorPalette.gray_900,
		backgroundHover: colorPalette.gray_200,
		backgroundDanger: colorPalette.red_50,
		colorDanger: colorPalette.red_500,
		backgroundDangerHover: colorPalette.red_100,
		colorDangerHover: colorPalette.red_700,
		icon: colorPalette.gray_700,
		iconHover: colorPalette.gray_800,
		backgroundSelected: colorPalette.blue_100,
		backgroundSelectedHover: colorPalette.blue_200,
		colorSelected: colorPalette.blue_500,
		colorSelectedHover: colorPalette.blue_700,
	},
	mainLabel: {
		color: colorPalette.blue_500,
	},
	table: {
		headerColor: colorPalette.gray_500,
		rowColor: colorPalette.gray_900,
		rowBackground: colorPalette.gray_100,
		borderColor: colorPalette.gray_300,
		priorityColor: colorPalette.gray_50,
		priorityBackground: colorPalette.gray_500,
		selectedColor: colorPalette.blue_600,
		selectedBackground: colorPalette.blue_100,
		dragIndicator: colorPalette.gray_300,
		selectedDragIndicator: colorPalette.blue_300,
	},
	schedulerColor: {
		blue: colorPalette.blue_600,
		yellow: colorPalette.yellow_600,
		teal: colorPalette.teal_600,
		pink: colorPalette.pink_600,
		purple: colorPalette.purple_600,
		red: colorPalette.red_600,
	},
	assetCard: {
		background: colorPalette.gray_50,
		backgroundSelected: colorPalette.blue_100,
		textMain: colorPalette.gray_900,
		textMainSelected: colorPalette.blue_500,
		textLight: colorPalette.gray_600,
		textLightSelected: colorPalette.blue_500,
		borderColor: colorPalette.gray_400,
		borderColorSelected: colorPalette.blue_500,
		previewBackgroundSelected: colorPalette.blue_100,
	},
	cardType: {
		playlistBackground: colorPalette.purple_50,
		playlistColor: colorPalette.purple_600,
		deviceBackground: colorPalette.teal_50,
		deviceColor: colorPalette.teal_600,
		packageBackground: colorPalette.blue_50,
		packageColor: colorPalette.blue_600,
	},
	navItem: {
		background: 'transparent',
		color: colorPalette.gray_800,
		inheritedInfoColor: colorPalette.gray_600,
		inheritedBorderColor: colorPalette.gray_400,
		inheritedBackground: colorPalette.gray_100,
		inheritedColor: colorPalette.gray_600,
		selectedBackground: colorPalette.blue_100,
		selectedColor: colorPalette.blue_500,
		selectedInheritedBorderColor: colorPalette.blue_600,
		highlightColor: colorPalette.teal_600,
		highlightBackground: colorPalette.teal_50,
	},
	list: {
		rowBackground: colorPalette.gray_100,
		rowBackgroundSelected: colorPalette.blue_100,
		rowBackgroundHover: colorPalette.gray_200,
		rowBackgroundSelectedHover: colorPalette.blue_200,
		headerBackground: colorPalette.gray_50,
		headerBackgroundSelected: colorPalette.blue_50,
		headerBackgroundHover: colorPalette.gray_100,
		headerBackgroundSelectedHover: colorPalette.blue_100,
	},
	message: {
		errorBackground: colorPalette.red_50,
		errorColor: colorPalette.red_600,
		warningBackground: colorPalette.yellow_100,
		warningColor: colorPalette.yellow_600,
		infoBackground: colorPalette.gray_200,
		infoColor: colorPalette.gray_700,
	},
	grantTypePill: {
		BrowserBackground: colorPalette.gray_200,
		BrowserNumberBackground: colorPalette.gray_300,
		BrowserColor: colorPalette.gray_700,
		STBBackground: colorPalette.purple_50,
		STBNumberBackground: colorPalette.purple_100,
		STBColor: colorPalette.purple_700,
		SignageBackground: colorPalette.teal_50,
		SignageNumberBackground: colorPalette.teal_100,
		SignageColor: colorPalette.teal_700,
		TabletBackground: colorPalette.blue_50,
		TabletNumberBackground: colorPalette.blue_100,
		TabletColor: colorPalette.blue_700,
		BedsideBackground: colorPalette.pink_50,
		BedsideNumberBackground: colorPalette.pink_100,
		BedsideColor: colorPalette.pink_700,
	},
	licenseStatus: {
		invalid: colorPalette.red_500,
		expired: colorPalette.yellow_600,
		expireSoon: colorPalette.yellow_400,
		notStartedYet: colorPalette.blue_500,
		startSoon: colorPalette.blue_300,
		valid: colorPalette.teal_500,
	},
}
