export const availableLanguages = [
	{ title: 'Abkhazian', id: 'ab' },
	{ title: 'Afaan Oromoo', id: 'om' },
	{ title: 'Afar', id: 'aa' },
	{ title: 'Afrikaans', id: 'af' },
	{ title: 'Akan', id: 'ak' },
	{ title: 'Amharic', id: 'am' },
	{ title: 'Aragonés', id: 'an' },
	{ title: 'Armenian', id: 'hy' },
	{ title: 'Assamese', id: 'as' },
	{ title: 'Avesta', id: 'ae' },
	{ title: 'Aymara', id: 'ay' },
	{ title: 'Azerbaijani', id: 'az' },
	{ title: 'Bahasa Indonesia', id: 'id' },
	{ title: 'bahasa Melayu', id: 'ms' },
	{ title: 'Bamanankan', id: 'bm' },
	{ title: 'Basa Jawa', id: 'jv' },
	{ title: 'basa Sunda', id: 'su' },
	{ title: 'Bashkir', id: 'ba' },
	{ title: 'Bengali', id: 'bn' },
	{ title: 'Bhutani', id: 'dz' },
	{ title: 'Bihari', id: 'bh' },
	{ title: 'Bislama', id: 'bi' },
	{ title: 'Bosanski jezik', id: 'bs' },
	{ title: 'Breton', id: 'br' },
	{ title: 'Byelorussian', id: 'be' },
	{ title: 'Catalan', id: 'ca' },
	{ title: 'Chamoru', id: 'ch' },
	{ title: 'chiCheŵa', id: 'ny' },
	{ title: 'chiShona', id: 'sn' },
	{ title: 'Corsu', id: 'co' },
	{ title: 'danske', id: 'da' },
	{ title: 'Deutsch', id: 'de' },
	{ title: 'Divehi', id: 'dv' },
	{ title: 'eesti keel', id: 'et' },
	{ title: 'Ekakairũ Naoero', id: 'na' },
	{ title: 'English', id: 'en' },
	{ title: 'español', id: 'es' },
	{ title: 'Esperanto', id: 'eo' },
	{ title: 'Euskara', id: 'eu' },
	{ title: 'faka-Tonga', id: 'to' },
	{ title: 'Fiji', id: 'fj' },
	{ title: 'finnish', id: 'fi' },
	{ title: 'français', id: 'fr' },
	{ title: 'Frysk', id: 'fy' },
	{ title: 'Fulfulde', id: 'ff' },
	{ title: 'Føroyskt', id: 'fo' },
	{ title: 'Gaeilge', id: 'ga' },
	{ title: 'Galego', id: 'gl' },
	{ title: 'Georgian', id: 'ka' },
	{ title: 'Ghaelg', id: 'gv' },
	{ title: 'Guarani', id: 'gn' },
	{ title: 'Gujarati', id: 'gu' },
	{ title: 'Gàidhlig', id: 'gd' },
	{ title: 'Gĩkũyũ', id: 'ki' },
	{ title: 'Hausa', id: 'ha' },
	{ title: 'Hebrew', id: 'he' },
	{ title: 'Hindi', id: 'hi' },
	{ title: 'Hiri Motu', id: 'ho' },
	{ title: 'hrvatski jezik', id: 'hr' },
	{ title: 'Ido', id: 'io' },
	{ title: 'Igbo', id: 'ig' },
	{ title: 'Interlingua', id: 'ia' },
	{ title: 'Interlingue', id: 'ie' },
	{ title: 'Inuktitut', id: 'iu' },
	{ title: 'Inupiaq', id: 'ik' },
	{ title: 'Iranian', id: '' },
	{ title: 'isiNdebele', id: 'nd' },
	{ title: 'isiXhosa', id: 'xh' },
	{ title: 'isiZulu', id: 'zu' },
	{ title: 'italiano', id: 'it' },
	{ title: 'Kajin M̧ajeļ', id: 'mh' },
	{ title: 'Kalaallisut', id: 'kl' },
	{ title: 'Kannada', id: 'kn' },
	{ title: 'Kanuri', id: 'kr' },
	{ title: 'Kashmiri', id: 'ks' },
	{ title: 'Kernewek', id: 'kw' },
	{ title: 'Khmer', id: 'km' },
	{ title: 'KiKongo', id: 'kg' },
	{ title: 'kiluba', id: 'lu' },
	{ title: 'kinyaRwanda', id: 'rw' },
	{ title: 'kiRundi', id: 'rn' },
	{ title: 'kiswahili', id: 'sw' },
	{ title: 'Kreyòl ayisyen', id: 'ht' },
	{ title: 'Kuanyama', id: 'kj' },
	{ title: 'Kurdî', id: 'ku' },
	{ title: 'Latine', id: 'la' },
	{ title: 'latviešu valoda', id: 'lv' },
	{ title: 'lietuvių kalba', id: 'lt' },
	{ title: 'Limburgs', id: 'li' },
	{ title: 'lingála', id: 'ln' },
	{ title: 'Luganda', id: 'lg' },
	{ title: 'Lëtzebuergesch', id: 'lb' },
	{ title: 'magyar', id: 'hu' },
	{ title: 'Malagasy fiteny', id: 'mg' },
	{ title: 'Malti', id: 'mt' },
	{ title: 'Māori', id: 'mi' },
	{ title: 'Navajo', id: 'nv' },
	{ title: 'Ndébélé', id: 'nr' },
	{ title: 'Nederlands', id: 'nl' },
	{ title: 'norsk', id: 'no' },
	{ title: 'norsk bokmål', id: 'nb' },
	{ title: 'norsk nynorsk', id: 'nn' },
	{ title: "O'zbek", id: 'uz' },
	{ title: 'occitan', id: 'oc' },
	{ title: 'Ojibwa', id: 'oj' },
	{ title: 'Otjiherero', id: 'hz' },
	{ title: 'Owambo', id: 'ng' },
	{ title: 'Persian', id: 'fa' },
	{ title: 'polski', id: 'pl' },
	{ title: 'português', id: 'pt' },
	{ title: 'Punjabi', id: 'pa' },
	{ title: 'Pushto', id: 'ps' },
	{ title: 'Quechua', id: 'qu' },
	{ title: 'română', id: 'ro' },
	{ title: 'rumantsch grischun', id: 'rm' },
	{ title: 'Samoan', id: 'sm' },
	{ title: 'Sango', id: 'sg' },
	{ title: 'sardu', id: 'sc' },
	{ title: 'seTswana', id: 'tn' },
	{ title: 'Shqip', id: 'sq' },
	{ title: 'Sichuan Yi', id: 'ii' },
	{ title: 'Sindhi', id: 'sd' },
	{ title: 'siSwati', id: 'ss' },
	{ title: 'slovenčina', id: 'sk' },
	{ title: 'slovenščina', id: 'sl' },
	{ title: 'Soomaaliga', id: 'so' },
	{ title: 'svenska', id: 'sv' },
	{ title: 'sámi', id: 'se' },
	{ title: 'Tagalog', id: 'tl' },
	{ title: 'Tahitian', id: 'ty' },
	{ title: 'Tibetan', id: 'bo' },
	{ title: 'Tiếng Việt', id: 'vi' },
	{ title: 'tshiVenḓa', id: 've' },
	{ title: 'Twi', id: 'tw' },
	{ title: 'Türkçe', id: 'tr' },
	{ title: 'Uighur', id: 'ug' },
	{ title: 'Urdu', id: 'ur' },
	{ title: 'Volapük', id: 'vo' },
	{ title: 'walon', id: 'wa' },
	{ title: 'Welsh', id: 'cy' },
	{ title: 'Wolof', id: 'wo' },
	{ title: 'xiTsonga', id: 'ts' },
	{ title: 'Yiddish', id: 'yi' },
	{ title: 'Yorùbá', id: 'yo' },
	{ title: 'Zhuang', id: 'za' },
	{ title: 'Íslenska', id: 'is' },
	{ title: 'čeština', id: 'cs' },
	{ title: 'Ɛʋɛgbɛ', id: 'ee' },
	{ title: 'Ελληνικά', id: 'el' },
	{ title: 'авар мацӀ', id: 'av' },
	{ title: 'български език', id: 'bg' },
	{ title: 'ирон ӕвзаг', id: 'os' },
	{ title: 'коми кыв', id: 'kv' },
	{ title: 'кыргыз тили', id: 'ky' },
	{ title: 'лимба молдовеняскэ', id: 'mo' },
	{ title: 'македонски јазик', id: 'mk' },
	{ title: 'монгол хэл', id: 'mn' },
	{ title: 'нохчийн мотт', id: 'ce' },
	{ title: 'русский язык', id: 'ru' },
	{ title: 'Словѣньскъ', id: 'cu' },
	{ title: 'српски', id: 'sr' },
	{ title: 'татарча', id: 'tt' },
	{ title: 'тоҷикӣ', id: 'tg' },
	{ title: 'Түркмен', id: 'tk' },
	{ title: 'українська мова', id: 'uk' },
	{ title: 'чӑваш чӗлхи', id: 'cv' },
	{ title: 'Қазақ тілі', id: 'kk' },
	{ title: 'العربية', id: 'ar' },
	{ title: 'नेपाली', id: 'ne' },
	{ title: 'पालि', id: 'pi' },
	{ title: 'मराठी', id: 'mr' },
	{ title: 'संस्कृतम्', id: 'sa' },
	{ title: 'ଓଡ଼ିଆ', id: 'or' },
	{ title: 'தமிழ்', id: 'ta' },
	{ title: 'తెలుగు', id: 'te' },
	{ title: 'മലയാളം', id: 'ml' },
	{ title: 'සිංහල', id: 'si' },
	{ title: 'ภาษาไทย', id: 'th' },
	{ title: 'ພາສາລາວ', id: 'lo' },
	{ title: 'မျန္မာစာ', id: 'my' },
	{ title: 'ትግርኛ', id: 'ti' },
	{ title: 'ᓀᐦᐃᔭᐍᐏᐣ', id: 'cr' },
	{ title: '中文', id: 'zh' },
	{ title: '日本語', id: 'ja' },
	{ title: '한국어', id: 'ko' },
]
