{{- if .Values.images.backend.replicaCount }}
apiVersion: v1
kind: Service
metadata:
    name: "{{ template "fullname" . }}-backend"
    labels:
        app: {{ template "name" . }}
        chart: {{ template "chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: "backend"
spec:
    ports:
        -   protocol: TCP
            port: 80
            name: http
            targetPort: http
        -   protocol: TCP
            port: 5701
            name: hz1
            targetPort: hz1
    selector:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        component: "backend"
{{- end }}
