{{- if .Values.images.backend.replicaCount }}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: "{{ template "fullname" . }}-backend"
    labels:
        app: {{ template "name" . }}
        chart: {{ template "chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: "backend"
spec:
    replicas: {{ .Values.images.backend.replicaCount }}
    selector:
        matchLabels:
            app: {{ template "name" . }}
            release: {{ .Release.Name }}
            component: "backend"
    template:
        metadata:
            labels:
                app: {{ template "name" . }}
                release: {{ .Release.Name }}
                component: "backend"
        spec:
            terminationGracePeriodSeconds: 190
            containers:
                -   name: "{{ .Chart.Name }}-backend"
                    image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag | default .Values.defaultTag | default .Chart.Version }}"
                    imagePullPolicy: "{{ .Values.pullPolicy }}"
                    ports:
                        -   containerPort: 80
                            name: http
                        -   containerPort: 5701
                            name: hz1
            {{- if or .Values.images.backend.debug .Values.images.backend.debugsuspend }}
                        -   containerPort: 5005
                            name: "jvm-debug"
            {{- end }}
                    env:
                        -   name: JAVA_OPTS
                            value: "{{ .Values.images.backend.javaOpts | default .Values.defaultJavaOpts }}{{ if .Values.images.backend.debug }} -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005{{ end }}{{ if .Values.images.backend.debugsuspend }} -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005{{ end }}"
                        -   name: JWT_SECRET
                            value: {{ .Values.jwtSecret }}
                        -   name: HAZELCAST_KUBERNETES_SERVICE
                            value: "{{ template "fullname" . }}"
                        -   name: HAZELCAST_KUBERNETES_NAMESPACE
                            value: "{{ .Release.Namespace }}"
                      {{- range $key, $value := .Values.images.backend.env }}
                        -   name: {{ $key }}
                            value: {{ $value | quote }}
                      {{- end }}
                    resources:
                        requests:
                            memory: {{ .Values.images.backend.memoryRequest | default .Values.defaultMemoryRequest | quote }}
                              {{- if .Values.images.backend.cpuRequest }}
                            cpu: {{ .Values.images.backend.cpuRequest | quote }}
                          {{- end }}
                        limits:
                            memory: {{ .Values.images.backend.memoryLimit | default .Values.images.backend.memoryRequest | default .Values.defaultMemoryRequest | quote }}
                              {{- if .Values.images.backend.cpuLimit }}
                            cpu: {{ .Values.images.backend.cpuLimit | quote }}
                        {{- end }}
                  {{- if not .Values.images.backend.noReadiness }}
                    readinessProbe:
                        httpGet:
                            path: /backend/actuator/health/readiness
                            port: 80
                        initialDelaySeconds: 30
                        periodSeconds: 15
                        timeoutSeconds: 1
                        successThreshold: 1
                        failureThreshold: 3
                  {{- end }}
                  {{- if not .Values.images.backend.noLiveness }}
                    livenessProbe:
                        httpGet:
                            path: /backend/actuator/health/liveness
                            port: 80
                        initialDelaySeconds: 900
                        periodSeconds: 15
                        timeoutSeconds: 2
                        successThreshold: 1
                        failureThreshold: 10
                  {{- end }}
            imagePullSecrets:
                -   name: regsecret
{{- end }}
