{{- if .Values.images.frontend.replicaCount }}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: "{{ template "fullname" . }}-frontend"
    labels:
        app: {{ template "name" . }}
        chart: {{ template "chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: "frontend"
spec:
    replicas: {{ .Values.images.frontend.replicaCount }}
    selector:
        matchLabels:
            app: {{ template "name" . }}
            release: {{ .Release.Name }}
            component: "frontend"
    template:
        metadata:
            labels:
                app: {{ template "name" . }}
                release: {{ .Release.Name }}
                component: "frontend"
        spec:
            containers:
                -   name: "{{ .Chart.Name }}-frontend"
                    image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag | default .Values.defaultTag | default .Chart.Version }}"
                    imagePullPolicy: "{{ .Values.pullPolicy }}"
                    ports:
                        -   containerPort: 80
                            name: http
                    env:
                      {{- range $key, $value := .Values.images.frontend.env }}
                        -   name: {{ $key }}
                            value: {{ $value | quote }}
                      {{- end }}
                    resources:
                        requests:
                            memory: {{ .Values.images.frontend.memoryRequest | quote }}
                              {{- if .Values.images.frontend.cpuRequest }}
                            cpu: {{ .Values.images.frontend.cpuRequest | quote }}
                          {{- end }}
                        limits:
                            memory: {{ .Values.images.frontend.memoryLimit | default .Values.images.frontend.memoryRequest | quote }}
                              {{- if .Values.images.frontend.cpuLimit }}
                            cpu: {{ .Values.images.frontend.cpuLimit | quote }}
                        {{- end }}
            imagePullSecrets:
                -   name: regsecret
{{- end }}
